apiVersion: apps/v1
kind: Deployment
metadata:
  name: openjdk-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openjdk
  template:
    metadata:
      labels:
        app: openjdk
    spec:
      containers:
        - name: openjdk
          image: nazmulislam76/spring-test:latest
          ports:
            - containerPort: 8080
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: openjdk-service
spec:
  selector:
    app: openjdk
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30090
  type: NodePort
